MVC/DBFirstMVCEX/DBFirstMVCEX/Models/CategoryTbl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryTbl
    {
        public CategoryTbl()
        {
            this.ProductTbls = new HashSet<ProductTbl>();
        }
    
        public long CategoryID { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<ProductTbl> ProductTbls { get; set; }
    }
}

MVC/DBFirstMVCEX/DBFirstMVCEX/Models/Company.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CurdMVC28Entities : DbContext
    {
        public CurdMVC28Entities()
            : base("name=CurdMVC28Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CategoryTbl> CategoryTbls { get; set; }
        public DbSet<ProductTbl> ProductTbls { get; set; }
    }
}

MVC/DBFirstMVCEX/DBFirstMVCEX/Models/Company.Designer.cs
// T4 code generation is enabled for model 'C:\Users\Ritesh\source\MVC\DBFirstMVCEX\DBFirstMVCEX\Models\Company.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

MVC/DBFirstMVCEX/DBFirstMVCEX/Models/Company.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

MVC/DBFirstMVCEX/DBFirstMVCEX/Models/ProductTbl.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirstMVCEX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTbl
    {
        public long ProductID { get; set; }
        public string ProductName { get; set; }
        public string MfgName { get; set; }
        public decimal Price { get; set; }
        public long CategoryID { get; set; }
    
        public virtual CategoryTbl CategoryTbl { get; set; }
    }
}

MVC/DBFirstMVCEX/DBFirstMVCEX/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBFirstMVCEX.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MVC/DBFirstMVCEX/DBFirstMVCEX/Controllers/TestController.cs
using DBFirstMVCEX.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DBFirstMVCEX.Controllers
{
    
    public class TestController : Controller
    {
        CurdMVC28Entities cc = new CurdMVC28Entities();
        // GET: Test
        public ActionResult Index()
        {
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            return View(this.cc.ProductTbls.ToList());
        }

        [HttpPost]
        public ActionResult SearchByName(string EName)
        {
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            if (EName=="" ||  EName==null)
            {
                return View(this.cc.ProductTbls.ToList());
            }
            else
            {
                var v = from m in this.cc.ProductTbls
                        where m.ProductName.StartsWith(EName)
                        select m;
                return View("Index",v.ToList());
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            return View();
        }
        [HttpPost]
        public ActionResult Create(ProductTbl rec)
        {
            if (ModelState.IsValid)
            {
                this.cc.ProductTbls.Add(rec);
                this.cc.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            return View();
        }

        [HttpGet]
        public ActionResult Edit(Int64 id)
        {
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            var rec=this.cc.ProductTbls.Find(id);
            return View(rec);
        }
        [HttpPost]
        public ActionResult Edit(ProductTbl rec)
        {
            if (ModelState.IsValid)
            {
                this.cc.Entry(rec).State = System.Data.EntityState.Modified;
                this.cc.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ProductID = new SelectList(this.cc.CategoryTbls.ToList(), "ProductID", "ProductName");
            return View(rec);
        }

        public ActionResult Delete(Int64 id)
        {
            var rec = this.cc.ProductTbls.Find(id);
            this.cc.ProductTbls.Remove(rec);
            this.cc.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MVC/DBFirstMVCEX/DBFirstMVCEX/Views/Test/Create.cshtml
@model DBFirstMVCEX.Models.ProductTbl
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <div> 
        <h2> Add Product Details </h2>
        <div>
            @using(Html.BeginForm())
            {
                <div>
                    @Html.LabelFor(p=>p.ProductName)
                    <div>
                        @Html.EditorFor(p=>p.ProductName)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p=>p.MfgName)
                    <div>
                        @Html.EditorFor(p=>p.MfgName)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p=>p.Price)
                    <div>
                        @Html.EditorFor(p=>p.Price)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p=>p.CategoryTbl.CategoryName)
                    <div>
                        @Html.DropDownList("CategoryID","Select Category")
                    </div>
                </div>

                <div>
                    <input type="submit" value="Save" />
                </div>
            }
        </div>
    </div>
</body>
</html>

MVC/DBFirstMVCEX/DBFirstMVCEX/Views/Test/Edit.cshtml
@model DBFirstMVCEX.Models.ProductTbl
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <div>
        <h2> Update Product Details </h2>
        <div>
            @using (Html.BeginForm())
            {
                @Html.HiddenFor(p=>p.ProductID)
                <div>
                    @Html.LabelFor(p => p.ProductName)
                    <div>
                        @Html.EditorFor(p => p.ProductName)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p => p.MfgName)
                    <div>
                        @Html.EditorFor(p => p.MfgName)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p => p.Price)
                    <div>
                        @Html.EditorFor(p => p.Price)
                    </div>
                </div>

                <div>
                    @Html.LabelFor(p => p.CategoryTbl.CategoryName)
                    <div>
                        @Html.DropDownList("CategoryID", "Select Category")
                    </div>
                </div>

                <div>
                    <input type="submit" value="Update" />
                </div>
            }
        </div>
    </div>
</body>
</html>

MVC/DBFirstMVCEX/DBFirstMVCEX/Views/Test/Index.cshtml
@model IEnumerable<DBFirstMVCEX.Models.ProductTbl>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
        <h2> Product List </h2>
        <div>
            @Html.ActionLink("Create New","Create")
            <table border="1">
                <thead>
                    <tr>
                        <td>
                            @using(Html.BeginForm("SearchByName","Test",FormMethod.Post))
            {
                             <span> Enter Name: </span>
                             <input type="text" name="EName" />
                             <input type="submit" value="Search" />
            }
                        </td>
                    </tr>
                </thead>
                <thead>
                    <tr>
                        <th align="center"> @Html.DisplayNameFor(p=>p.ProductID) </th>
                        <th align="center"> @Html.DisplayNameFor(p=>p.ProductName) </th>
                        <th align="center"> @Html.DisplayNameFor(p=>p.MfgName) </th>
                        <th align="center"> @Html.DisplayNameFor(p=>p.CategoryTbl.CategoryName) </th>
                        <th align="center"> @Html.DisplayNameFor(p=>p.Price) </th>
                        <th> Actions </th>
                    </tr>
                </thead>
                @foreach(var temp in Model)
            {
                <tr>
                    <td align="center"> @Html.DisplayFor(p => temp.ProductID) </td>
                    <td align="center"> @Html.DisplayFor(p => temp.ProductName) </td>
                    <td align="center"> @Html.DisplayFor(p => temp.MfgName) </td>
                    <td align="center"> @Html.DisplayFor(p => temp.CategoryTbl.CategoryName) </td>
                    <td align="center"> @Html.DisplayFor(p => temp.Price) </td>
                    <td align="center">
                        @Html.ActionLink("Edit", "Edit", new { id = temp.ProductID })
                        @Html.ActionLink("Delete", "Delete", new { id = temp.ProductID })
                    </td>
                </tr>
            }
            </table>
        </div>
    </div>
</body>
</html>