Core/TagHelpersEX/TagHelpersEX/Models/City.cs
using System;
using System.Collections.Generic;

namespace TagHelpersEX.Models
{
    public class City
    {
        public Int64 CityID { get; set; }
        public string CityName { get; set; }

        public static List<City> GetAllCities()
        {
            List<City> ct = new List<City>();
            ct.Add(new City() { CityID = 1,CityName="Pune" });
            ct.Add(new City() { CityID = 2, CityName = "Mumbai" });
            ct.Add(new City() { CityID = 3, CityName = "Delhi" });
            ct.Add(new City() { CityID = 4, CityName = "Noida" });
            ct.Add(new City() { CityID = 5, CityName = "Chennai" });

            return ct;
        }
    }
}

Core/TagHelpersEX/TagHelpersEX/Models/Customer.cs
using System;
using TagHelpersEX.ENum;

namespace TagHelpersEX.Models
{
    public class Customer
    {
        public Int64 CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public Int64 CityID { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public CusCategoryENum CustomerCategory { get; set; }
    }
}

Core/TagHelpersEX/TagHelpersEX/Controllers/ABCController.cs
using Microsoft.AspNetCore.Mvc;
using TagHelpersEX.Models;

namespace TagHelpersEX.Controllers
{
    public class ABCController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public string SayHello(string str, string id)
        {
            return "String str:" + str + "string Id:" + id;
        }
        [HttpPost]
        public IActionResult Save(Customer rec)
        {
            return View(); 
        }
        
    }
}

Core/TagHelpersEX/TagHelpersEX/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using TagHelpersEX.Models;

namespace TagHelpersEX.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.ct = new SelectList(City.GetAllCities(), "CityID", "CityName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Customer rec)
        {
            return RedirectToAction("Index");
        }
    }
}

Core/TagHelpersEX/TagHelpersEX/Views/Home/About.cshtml
<html>
    <head>
        <title> Home-About </title>
    </head>
    <h2> About </h2>
    <body>
        <p>
            This is about action from home controller 
        </p>
    </body>
</html>

Core/TagHelpersEX/TagHelpersEX/Views/Home/Create.cshtml
@model Customer

<html>
<head>
    <title> Customer </title>
</head>
<body>
    <form asp-controller="ABC" asp-action="Save" method="post">
        <div>
            <label asp-for="CustomerName"></label>
           <div>
            <input asp-for="CustomerName" />
           </div>
        </div>

        <div>
            <label asp-for="Address"></label>
            <div>
               <textarea asp-for="Address"></textarea>
            </div>
        </div>
        
        <div>
            <label asp-for="EmailID"></label>
        <div>
            <input asp-for="EmailID" />
        </div>
        </div>

        <div>
            <label asp-for="MobileNo"></label>
           <div>
            <input asp-for="MobileNo" />
           </div>
        </div>

        <div>
            <label> Select City </label>
            <div>
                <select asp-for="CityID" asp-items="@ViewBag.ct"> 
                    <options> Select City </options>
                </select>
            </div>
        </div>

        <div>
            <label> Customer Category </label>
            <div>
                <select asp-for="CustomerCategory" asp-items="@Html.GetEnumSelectList<CusCategoryENum>()">
                    <option> Select Category </option>
                </select>
            </div>
        </div>

        <div>
           <input type="submit" value="Submit" />
        </div>
    </form>
</body>
</html>

Core/TagHelpersEX/TagHelpersEX/Views/Home/Index.cshtml
<html>
    <head>
        <title> Home-Index </title>
    </head>
    <h2> Index </h2>
    <body>
        <h2> Welcome to Home Index </h2>
        <a asp-controller="Home" asp-action="About"> Go to About </a> <br />
        <a asp-controller="ABC" asp-action="Index"> Go to Index </a> <br />
        <a asp-controller="ABC" asp-action="SayHello" asp-route-str="abc@gmail.com" asp-route-id="visual@hotmail.com"> Go to SayHello </a> <br />
        <a asp-controller="Home" asp-action="Create"> Go to Form </a>
    </body>
</html>